// notes/src/components/NoteEditor.vue
<template>
  <div class="note-editor">
    <p class="note-editor-info">{{ selectedNote.timestamp | formatTimestamp }}</p>
    <textarea class="note-editor-input"
      v-bind:value="selectedNote.body"
      v-on:input="input($event)"
    >
    </textarea>
  </div>
</template>

<script>
export default {
  name: 'note-editor',
  props: ['selectedNote'],
  methods: {
    input: function($event) {
      this.$emit('inputNoteEditor', $event.target.value);
    }
  }
};
</script>

<style>
/* LAYOUT */
.note-editor {
  display: flex;
  flex: 1;
  flex-direction: column;
}
.note-editor-info {
  padding: 0.5em;
  text-align: center;
}
.note-editor-input {
  display: flex;
  flex: 1;
  width: 100%;
  padding: 0 2em 0 2em;
}
/* COLORS */
.note-editor-info {
  color: #DCDADC;
}
/* TYPOGRAPHY */
.note-editor, .note-editor-input {
  font-size: 0.9em;
}
</style>

// notes-react/src/components/NoteEditor.js
import React, { Component } from "react";
import { formatTimestamp } from "../helpers";

class NoteEditor extends Component {
  handleChange = event => {
    this.props.onNoteEditorChange(event.target.value);
  };
  render() {
    if (this.props.selectedNote) {
      return (
        <div className="note-editor">
          <p className="note-editor-info">
            {formatTimestamp(this.props.selectedNote.timestamp)}
          </p>
          <textarea
            className="note-editor-input"
            value={this.props.selectedNote.body}
            onChange={this.handleChange}
          />
        </div>
      );
    } else {
      return null;
    }
  }
}

export default NoteEditor;
